media:
  - name: media
    label: Media
    input: src/assets/media
    output: /assets/media

content:
  - name: posts
    label: Blog posts
    type: collection
    path: src/posts
    view:
      fields: [title, date, published]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: published
        label: Published
        type: boolean
        default: true
      - name: tags
        label: Tags
        type: list
        items:
          type: string
      - name: layout
        label: Layout
        type: string
        default: layouts/post.liquid
        hidden: true
      - name: body
        label: Body
        type: rich-text

  - name: site
    label: Site settings
    type: file
    path: src/_data/site.json
    fields:
      - name: title
        label: Site title
        type: string
      - name: description
        label: Description
        type: string
